spring:
  datasource:
    url: jdbc:mysql://localhost:3306/posco_db1
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false

logging:
  level:
#    org.springframework: DEBUG