spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/posco_db1
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
#    org.springframework: DEBUG